# Generated by Django 2.2.5 on 2019-09-14 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bloodgroup',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='currentlocation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('howmanybagsofblood', models.IntegerField()),
                ('patientdisease', models.TextField()),
                ('admittedhospitalname', models.CharField(max_length=75)),
                ('deadlinedate', models.DateField()),
                ('deadlinetime', models.TimeField()),
                ('currentlocation', models.CharField(max_length=50)),
                ('phonenumber', models.BigIntegerField()),
                ('relationwithruetians', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
