# Generated by Django 2.2.5 on 2019-09-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_post_posteddatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posttitle',
            field=models.CharField(default='Blood Request post', max_length=150),
        ),
    ]
