# Generated by Django 2.2.5 on 2019-09-26 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190926_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posteddatetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 0, 23, 33, 244379, tzinfo=utc)),
        ),
    ]
