# Generated by Django 2.2.5 on 2019-09-28 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190927_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='patientdisease',
            field=models.CharField(default='Blood Request post', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='posteddatetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 28, 14, 51, 53, 916351, tzinfo=utc)),
        ),
    ]
